class IntegrationPhase:
  LOCATE_ROSBAG_1_GRAIN = 10
  LOCATE_ROSBAG_2_PROCEDURE = 11
  LOCATE_ROSBAG_3_GRAIN_FACTORY = 12
  LOCATE_ROSBAG_WITH_RUNNER = 13
  # 나중에 연구 늘어나면 여기만 추가
  # PROCEDURE_ANALYZE = 40
